const DAY=86400000;
const iso=d=>new Date(d).toISOString().slice(0,10);
const today=()=>iso(new Date());
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const $=s=>document.querySelector(s);

const copy={
  en:{greeting:"Good afternoon, Zora.",subtitle:"A calm home starts with one small thing.",todayTasks:"Today’s Tasks",schedule:"Schedule",viewAll:"View all tasks",addSchedule:"Add scheduled task",quickActions:"Quick Actions",makeItEasy:"Make it easy",dailyTask:"Daily task",everyDay:"Every day",scheduledTask:"Scheduled",chooseRepeat:"Choose a repeat",flexibleTask:"Flexible",wheneverReady:"Whenever you’re ready",dashboard:"Dashboard",tasks:"Tasks",settings:"Settings",addTask:"Add task",englishName:"English name",chineseName:"Chinese name",taskType:"Task type",repeatEvery:"Repeat every",unit:"Unit",days:"Days",weeks:"Weeks",months:"Months",followUp:"Next-day follow-up (optional)",saveTask:"Save task",allTasks:"All tasks",language:"Language",languageHelp:"Switch between English and Chinese",weatherLocation:"Weather location",locate:"Locate",install:"Install Homebase",installHelp:"Add this dashboard to your Home Screen",installButton:"Install",reset:"Reset all local data",all:"All",today:"Today",noTasks:"Nothing waiting here.",deleteConfirm:"Delete this task?",resetConfirm:"Reset every task and completion record?",saved:"Task saved",weatherError:"Weather unavailable",locationDenied:"Location access was not available",installed:"Homebase is ready to install",installIos:"On iPhone, tap Share, then Add to Home Screen."},
  zh:{greeting:"下午好，左拉。",subtitle:"从一件小事开始，让家慢慢变得舒适。",todayTasks:"今日任务",schedule:"日程",viewAll:"查看全部任务",addSchedule:"添加计划任务",quickActions:"快捷操作",makeItEasy:"让一切更简单",dailyTask:"每日任务",everyDay:"每天重复",scheduledTask:"计划任务",chooseRepeat:"选择循环周期",flexibleTask:"灵活任务",wheneverReady:"准备好时再开始",dashboard:"主页",tasks:"任务",settings:"设置",addTask:"添加任务",englishName:"英文名称",chineseName:"中文名称",taskType:"任务类型",repeatEvery:"每隔",unit:"单位",days:"天",weeks:"周",months:"月",followUp:"次日跟进（选填）",saveTask:"保存任务",allTasks:"全部任务",language:"语言",languageHelp:"切换中文或英文",weatherLocation:"天气地点",locate:"定位",install:"安装 Homebase",installHelp:"将工作台添加到手机主屏幕",installButton:"安装",reset:"清空本地数据",all:"全部",today:"今日",noTasks:"这里暂时没有任务。",deleteConfirm:"删除这项任务？",resetConfirm:"清空所有任务和完成记录？",saved:"任务已保存",weatherError:"暂时无法获取天气",locationDenied:"无法使用当前位置",installed:"Homebase 已可以安装",installIos:"iPhone 请点击分享，再选择“添加到主屏幕”。"}
};

const defaults=[
  {id:uid(),zh:"洗碗",en:"Wash dishes",type:"daily"},{id:uid(),zh:"洗猫碗",en:"Wash Meatball’s bowls",type:"daily"},{id:uid(),zh:"铲猫砂",en:"Scoop litter",type:"daily"},{id:uid(),zh:"扫地",en:"Sweep floors",type:"daily"},
  {id:uid(),zh:"擦餐桌",en:"Wipe dining table",type:"scheduled",unit:"days",every:3,start:today()},{id:uid(),zh:"吸地毯",en:"Vacuum carpets",type:"scheduled",unit:"days",every:3,start:today()},{id:uid(),zh:"清理厨房",en:"Clean kitchen",type:"scheduled",unit:"weeks",every:1,start:today()},{id:uid(),zh:"清理浴室",en:"Clean bathroom",type:"scheduled",unit:"weeks",every:2,start:today()},{id:uid(),zh:"洗衣服",en:"Do laundry",type:"flexible",followupZh:"收衣服",followupEn:"Put clothes away"}
];
const stored=JSON.parse(localStorage.getItem("cleaningState")||"null");
let state=stored||{tasks:defaults,done:{},deferred:{},generated:[],activeTab:"today"};
state.tasks=state.tasks||defaults;state.done=state.done||{};state.deferred=state.deferred||{};state.generated=state.generated||[];state.lang=state.lang||localStorage.getItem("homebaseLang")||"en";
let taskFilter="all",deferredPrompt=null;
const save=()=>{localStorage.setItem("cleaningState",JSON.stringify(state));localStorage.setItem("homebaseLang",state.lang)};
const addDays=(s,n)=>{const d=new Date(s+"T12:00:00");d.setDate(d.getDate()+n);return iso(d)};
const diffDays=(a,b)=>Math.floor((new Date(a+"T12:00:00")-new Date(b+"T12:00:00"))/DAY);
const monthDiff=(a,b)=>(new Date(a).getFullYear()-new Date(b).getFullYear())*12+new Date(a).getMonth()-new Date(b).getMonth();
const keyFor=(id,date)=>`${id}@${date}`;
const t=k=>copy[state.lang][k]||k;
const taskName=task=>state.lang==="zh"?(task.zh||task.en):(task.en||task.zh);

function due(task,date){
  if(task.type==="daily") return true;if(task.type!=="scheduled") return false;
  const dd=diffDays(date,task.start||today());if(dd<0)return false;const every=Math.max(1,Number(task.every)||1);
  if(task.unit==="days")return dd%every===0;if(task.unit==="weeks")return dd%(7*every)===0;
  if(task.unit==="months"){const md=monthDiff(date,task.start||today());return md>=0&&md%every===0&&new Date(date).getDate()===new Date((task.start||today())+"T12:00:00").getDate()}return false;
}
function instances(date){
  const items=state.tasks.filter(task=>due(task,date)).map(task=>({...task,date,key:keyFor(task.id,date)}));
  state.generated.filter(task=>task.date===date).forEach(task=>items.push({...task,key:keyFor(task.id,date)}));
  Object.entries(state.deferred).forEach(([key,to])=>{if(to===date&&!state.done[key]){const id=key.split("@")[0],task=state.tasks.find(x=>x.id===id)||state.generated.find(x=>x.id===id);if(task&&!items.some(x=>x.key===key))items.unshift({...task,date,key,overdue:true})}});
  return items;
}
function autoDefer(){const current=today(),previous=addDays(current,-1);state.tasks.filter(x=>due(x,previous)).forEach(task=>{const key=keyFor(task.id,previous);if(!state.done[key]&&!state.deferred[key])state.deferred[key]=current});Object.keys(state.deferred).forEach(key=>{if(!state.done[key]&&state.deferred[key]<current)state.deferred[key]=current});save()}
function toggleDone(item){if(state.done[item.key])delete state.done[item.key];else{state.done[item.key]=new Date().toISOString();delete state.deferred[item.key];if(item.type==="flexible"&&(item.followupEn||item.followupZh)&&!state.generated.some(x=>x.parentKey===item.key))state.generated.push({id:uid(),en:item.followupEn||item.followupZh,zh:item.followupZh||item.followupEn,type:"generated",date:addDays(item.date,1),parentKey:item.key})}save();render()}
function taskRow(item,library=false){const el=document.createElement("div");const key=item.key||keyFor(item.id,today()),done=!!state.done[key];el.className=`task-item${done?" done":""}`;el.innerHTML=`<button class="check" type="button">${done?"✓":""}</button><div><div class="task-name"></div><div class="task-meta"></div></div>${library?'<button class="delete-task" type="button" aria-label="Delete">×</button>':""}`;el.querySelector(".task-name").textContent=taskName(item);el.querySelector(".task-meta").textContent=item.overdue?`${t("today")} · ↗`:typeLabel(item);el.querySelector(".check").onclick=()=>toggleDone({...item,key,date:item.date||today()});if(library)el.querySelector(".delete-task").onclick=()=>removeTask(item.id);return el}
function typeLabel(task){if(task.type==="daily")return t("dailyTask");if(task.type==="flexible")return t("flexibleTask");if(task.type==="generated")return t("followUp");const unit=t(task.unit||"days").toLowerCase();return `${t("scheduledTask")} · ${task.every||1} ${unit}`}
function removeTask(id){if(confirm(t("deleteConfirm"))){state.tasks=state.tasks.filter(x=>x.id!==id);state.generated=state.generated.filter(x=>x.id!==id);save();render()}}
function renderToday(){const items=instances(today()),list=$("#todayList");list.innerHTML="";items.slice(0,5).forEach(item=>list.appendChild(taskRow(item)));if(!items.length)list.innerHTML=`<div class="empty">${t("noTasks")}</div>`;$("#todayCount").textContent=`${items.filter(x=>state.done[x.key]).length} / ${items.length}`}
function nextScheduled(){const out=[];for(let offset=0;offset<32&&out.length<3;offset++){const date=addDays(today(),offset);state.tasks.filter(x=>x.type==="scheduled"&&due(x,date)).forEach(task=>out.push({...task,date}))}return out.slice(0,3)}
function renderSchedule(){const list=$("#scheduleList");list.innerHTML="";nextScheduled().forEach(item=>{const d=new Date(item.date+"T12:00:00"),el=document.createElement("div");el.className="schedule-item";el.innerHTML=`<div class="date-badge"><strong>${d.getDate()}</strong><small>${new Intl.DateTimeFormat(state.lang==="zh"?"zh-CN":"en-NZ",{month:"short"}).format(d)}</small></div><div><h3></h3><p></p></div>`;el.querySelector("h3").textContent=taskName(item);el.querySelector("p").textContent=new Intl.DateTimeFormat(state.lang==="zh"?"zh-CN":"en-NZ",{weekday:"long"}).format(d);list.appendChild(el)});if(!list.children.length)list.innerHTML=`<div class="empty">${t("noTasks")}</div>`}
function renderLibrary(){const filters=["all","dailyTask","scheduledTask","flexibleTask"],wrap=$("#taskFilters");wrap.innerHTML="";filters.forEach((label,i)=>{const value=["all","daily","scheduled","flexible"][i],button=document.createElement("button");button.type="button";button.className=`filter-button${taskFilter===value?" active":""}`;button.textContent=t(label);button.onclick=()=>{taskFilter=value;renderLibrary()};wrap.appendChild(button)});const list=$("#allTasksList");list.innerHTML="";state.tasks.filter(x=>taskFilter==="all"||x.type===taskFilter).forEach(item=>list.appendChild(taskRow(item,true)));if(!list.children.length)list.innerHTML=`<div class="empty">${t("noTasks")}</div>`}
function applyLanguage(){document.documentElement.lang=state.lang==="zh"?"zh-CN":"en";document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));$("#languageBtn").textContent=state.lang==="en"?"中":"EN";$("#settingsLanguageBtn").textContent=state.lang==="en"?"中文":"English";const hour=new Date().getHours();if(state.lang==="en")$("[data-i18n=greeting]").textContent=`Good ${hour<12?"morning":hour<18?"afternoon":"evening"}, Zora.`;$("#dateLine").textContent=new Intl.DateTimeFormat(state.lang==="zh"?"zh-CN":"en-NZ",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}
function render(){autoDefer();applyLanguage();renderToday();renderSchedule();renderLibrary()}
function openModal(id){const el=$("#"+id);el.classList.add("show");el.setAttribute("aria-hidden","false")}
function closeModal(id){const el=$("#"+id);el.classList.remove("show");el.setAttribute("aria-hidden","true")}
function openTask(type="daily"){$("#taskForm").reset();$("#repeatEvery").value=1;$("#taskType").value=type;toggleTaskFields();openModal("taskModal");setTimeout(()=>$("#nameEn").focus(),120)}
function toggleTaskFields(){const type=$("#taskType").value;$("#scheduledFields").hidden=type!=="scheduled";$("#flexFields").hidden=type!=="flexible"}
function switchLanguage(){state.lang=state.lang==="en"?"zh":"en";save();render()}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove("show"),2400)}

const weatherCodes={0:"☀️",1:"🌤️",2:"⛅",3:"☁️",45:"🌫️",48:"🌫️",51:"🌦️",53:"🌦️",55:"🌧️",61:"🌧️",63:"🌧️",65:"🌧️",71:"🌨️",73:"🌨️",75:"❄️",80:"🌦️",81:"🌧️",82:"⛈️",95:"⛈️"};
async function getWeather(lat=-43.5321,lon=172.6362,label="Christchurch"){try{const response=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code&timezone=auto`);if(!response.ok)throw new Error();const data=await response.json();$("#weatherTemp").textContent=`${Math.round(data.current.temperature_2m)}°`;$("#weatherIcon").textContent=weatherCodes[data.current.weather_code]||"☁️";$("#weatherPlace").textContent=label;localStorage.setItem("homebaseWeather",JSON.stringify({lat,lon,label}))}catch(e){toast(t("weatherError"))}}
function useLocation(){if(!navigator.geolocation){toast(t("locationDenied"));return}navigator.geolocation.getCurrentPosition(pos=>{getWeather(pos.coords.latitude,pos.coords.longitude,state.lang==="zh"?"当前位置":"My location");closeModal("settingsModal")},()=>toast(t("locationDenied")),{timeout:8000})}

$("#languageBtn").onclick=switchLanguage;$("#settingsLanguageBtn").onclick=switchLanguage;$("#settingsBtn").onclick=()=>openModal("settingsModal");$("#addBtn").onclick=()=>openTask();$("#viewTasksBtn").onclick=()=>openModal("tasksModal");$("#addScheduleBtn").onclick=()=>openTask("scheduled");$("#taskType").onchange=toggleTaskFields;$("#weatherBtn").onclick=()=>{const saved=JSON.parse(localStorage.getItem("homebaseWeather")||"null");saved?getWeather(saved.lat,saved.lon,saved.label):getWeather()};$("#locationBtn").onclick=useLocation;
document.querySelectorAll("[data-add-type]").forEach(button=>button.onclick=()=>openTask(button.dataset.addType));document.querySelectorAll("[data-close]").forEach(button=>button.onclick=()=>closeModal(button.dataset.close));document.querySelectorAll(".modal").forEach(modal=>modal.onclick=e=>{if(e.target===modal)closeModal(modal.id)});
document.querySelectorAll(".nav-item").forEach(button=>button.onclick=()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));button.classList.add("active");const view=button.dataset.view;if(view==="tasks")openModal("tasksModal");if(view==="schedule")openTask("scheduled");if(view==="settings")openModal("settingsModal")});
$("#taskForm").onsubmit=e=>{e.preventDefault();const type=$("#taskType").value,item={id:uid(),en:$("#nameEn").value.trim(),zh:$("#nameZh").value.trim(),type};if(type==="scheduled")Object.assign(item,{unit:$("#repeatUnit").value,every:Math.max(1,Number($("#repeatEvery").value)||1),start:today()});if(type==="flexible")Object.assign(item,{followupEn:$("#followupEn").value.trim(),followupZh:$("#followupZh").value.trim()});state.tasks.push(item);save();closeModal("taskModal");toast(t("saved"));render()};
$("#resetBtn").onclick=()=>{if(confirm(t("resetConfirm"))){localStorage.removeItem("cleaningState");localStorage.removeItem("homebaseLang");location.reload()}};
let installPrompt=null;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;toast(t("installed"))});$("#installBtn").onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else toast(t("installIos"))};
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");
const savedWeather=JSON.parse(localStorage.getItem("homebaseWeather")||"null");savedWeather?getWeather(savedWeather.lat,savedWeather.lon,savedWeather.label):getWeather();render();
